Add new profile windwos-executable
Viascom/groundwork pull request #10
Opened 2016-12-01 10:32 UTC by nikolastankovic

Add new profile windwos-executable for building .exe packages direct
from maven.

2016-12-01 10:44 UTC, itsmefox requested changes

2016-12-01 10:44 UTC, patrickboesch commented on pom/pom.xml
>          <executable.jar.finalName>executable-output</executable.jar.finalName>
Use here also ${executable.finalName} or delete if not needed

2016-12-01 10:44 UTC, patrickboesch commented on pom/pom.xml
> +                </plugin>
Why we have to redefine `maven-compiler-plugin`? Its is already defined in `build / plugins`

2016-12-01 10:44 UTC, patrickboesch commented on pom/pom.xml
> +                                <downloadUrl>http://java.com/download</downloadUrl>
What is the purpose of this property?

2016-12-01 10:44 UTC, patrickboesch commented on pom/pom.xml
> +        <!-- Windows executable -->
Rename to `<!-- Default Windows executable settings -->`

2016-12-01 10:44 UTC, patrickboesch commented on pom/pom.xml
>          <!-- Default executable jar main class -->
Rename to `<!-- Default Jar executable settings -->`

2016-12-01 11:35 UTC, nikolastankovic commented on pom/pom.xml
> +                                <downloadUrl>http://java.com/download</downloadUrl>
To download if not installed the JRE.

2016-12-01 16:46 UTC, itsmefox requested changes

2016-12-01 16:46 UTC, patrickboesch commented on pom/pom.xml
>                  <plugin>
This plugin (`maven-compiler-plugin`) is already global defined in `build / plugins` and you don't need to add this again.
See [Line 465](https://github.com/Viascom/groundwork/blob/7fd66d0b3680915a2f7daee16058e32d96a202b8/pom/pom.xml#L465)

2016-12-01 19:05 UTC, nikolastankovic commented on pom/pom.xml
>                  <plugin>
ok it's now removed ... my fault

2016-12-02 08:17 UTC, itsmefox approved these changes

2016-12-02 08:17 UTC, merged